clusters = source, target
source.bootstrap.servers = kafka:29092
target.bootstrap.servers = kafka-2:29092

source->target.enabled = true
source->target.topics = bess-data
source->target.groups.blacklist = console-consumer-.*,__.*
source->target.sync.topic.configs.enabled = true
source->target.checkpoints.topic.replication.factor = 1
source->target.heartbeats.topic.replication.factor = 1
source->target.offset-syncs.topic.replication.factor = 1
source->target.offset-syncs.topic.partitions = 1

tasks.max = 1
